# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/alerts.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "system"
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: "app-2048"
    static_configs:
      - targets: ["host.docker.internal:5000"]

  - job_name: "mongo-2048"
    static_configs:
      - targets: ["host.docker.internal:9216"]

  # - job_name: 'docker-sd'
  #   docker_sd_configs:
  #     - host: "tcp://host.docker.internal:2375"
  #       refresh_interval: 10s
